GUNDI-3128: Webhooks Support
PADAS/gundi-integration-action-runner pull request #12
Opened 2024-06-10 20:26 UTC by marianobrc

### What does this PR do?
- Adds support for webhooks
- Adds utilities for generic json-to-json transformations
- Adds utilities for parsing binary data that is encoded as hex strings
- Updates self-registration to register webhook integrations in Gundi
- Adds basic test coverage for webhooks
- Adds usage instructions in the README for webhooks

#### Other improvements unrelated to webhooks
- Upgrade python version to v3.10
- Retry Redis errors in the state manager
- Allow enabling/disabled background processing

### Relevant link(s)
[GUNDI-3128](https://allenai.atlassian.net/browse/GUNDI-3128)

[GUNDI-3128]: https://allenai.atlassian.net/browse/GUNDI-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-10 20:48 UTC, daniefdz requested changes

2024-06-10 20:48 UTC, daniefdz commented on docker/Dockerfile
> +RUN pip install --upgrade pip
Let's merge both RUN statements.
`RUN pip install --upgrade pip && pip install -r /code/requirements.txt`

2024-06-10 23:32 UTC, marianobrc commented on docker/Dockerfile
> +RUN pip install --upgrade pip
Good idea, thanks

2024-06-10 23:55 UTC, daniefdz approved these changes
infra side LGTM

2024-06-11 06:01 UTC, chrisdoehring commented on app/services/utils.py
> +class DyntamicFactory:
Great find.

2024-06-11 11:42 UTC, chrisdoehring approved these changes

2024-06-11 12:08 UTC, merged